version: '3'
services:
  alice-bob-and-random-numbers:
    environment:
      - PASSWORD=__TEAM_SECRET__
    build:
      context: .
    restart: always
    volumes:
    - "__FLAG_DIR__:/flag:ro"
    ports:
    - "__PORT__:9999"